# Nome do workflow
name: experimento-ci-cd

# Evento que aciona o workflow: toda vez que for criado um Pull Request para a branch main
on:
  pull_request:
    branches:
      - main

# Cancela execuções antigas obsoletas na mesma branch
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Habilita cache para otimização de velocidade

      - name: Instalação e Testes (Backend)
        working-directory: ./backend
        run: |
          npm ci
          npm run generate # Necessário para o Prisma
          npm test -- --coverage

  build-and-integration:
    needs: tests
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: adote_facil
      POSTGRES_HOST: adote-facil-postgres
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_PORT: 5432
      POSTGRES_CONTAINER_PORT: 6500
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configurar Variáveis de Ambiente
        working-directory: ./backend
        run: |
          echo "POSTGRES_DB=${{ env.POSTGRES_DB }}" > .env
          echo "POSTGRES_HOST=${{ env.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_USER=${{ env.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_PORT=${{ env.POSTGRES_PORT }}" >> .env
          echo "POSTGRES_CONTAINER_PORT=${{ env.POSTGRES_CONTAINER_PORT }}" >> .env

      - name: Subir containers em background
        run: docker compose up -d --build

      - name: Validação de Integridade dos Containers
        run: |
          sleep 10 # Tempo para estabilização dos serviços
          if [ $(docker inspect -f '{{.State.Running}}' adote-facil-backend) = "false" ]; then exit 1; fi
          if [ $(docker inspect -f '{{.State.Running}}' adote-facil-frontend) = "false" ]; then exit 1; fi

      - name: Desligar containers
        if: always()
        run: docker compose down


  # Quarto job: Geração e entrega do artefato do projeto
  delivery:
    needs: build  # Esse job também depende do job 'build'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Gerar arquivo ZIP do projeto completo
        run: zip -r adote-facil-projeto.zip . -x '*.git*' '*.github*' 'node_modules/*'
        # Compacta todos os arquivos do repositório, exceto pastas desnecessárias como .git, .github e node_modules

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: adote-facil-projeto  # Nome do artefato que aparecerá na aba de artefatos da execução
          path: adote-facil-projeto.zip  # Caminho do arquivo que será enviado
